language: node_js
node_js:
- 'stable'
deploy:
  api_key:
    secure: TtYVVXzDerlSHb4q3dOHK3NWijJvEmb5vIms5M2/EwDFCFNlMgXWhV+NCm4BxTZnu5bIEUTHu+dK5lJpHUXi9R2U1Jz+4sskKKGcT80JQtJ62qGxsrpcGl2vF+UNtDvQY7zEpbW0Lcoef8YG1h7hPoTpA383v6ouVVMNFTfqVj+V7yMCOWALRt+O8OA1yqsvNGqpNw8b0FJz09IpJ5lB1CvZwj5yM0cxaoNdcZRH7oGSqF4bu5MKbxLzk9siok0rmekHpK1x1ymXbdJ8O8UqNc6Fr6dYrrR0ZAGAiuc6rdYqFadXJgDXF6gw9v8rq2Rizr9Nf+Cj/Y/ksS1ZDhVsJ2EbzTVqtnklGJAgDL9/yF/RzavUk0C6ZehcrTg4GYS3YKjxQY8ZaKGsPo6YAN0eL6+8vfZjL8mek/eJbpHcxIQvSyxKL1YFMlW59O9djruWor447GYlUYHarxWNQXT/yu1gZ9jxoEGTeJwSbshmlV5S2JUWPn65uxUcpVzuCLZm9+NzbnrE2Vi+1IiG7F75Ck0ceYfNn9jvosRlfSJ3R/+iwOAAM2y+PjEt0y9l3TErcX4NsDlw9eY5Jm4ZixxXAM7+VUJN74dZ+G/7dl+7kYKoplP+SPIjfs3ftDJJhSdEVUBnUqCwJy6dvxs0f4OCYYX4wrcj+6CRgB0SApZfdWs=
  provider: heroku
  strategy: api
  on:
    all_branches: false
  app:
    master: harvest-api-staging
    production: harvest-api-prod
    develop: harvest-api-dev